apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: shopsphere

type: Opaque

stringData:

  DB_URL: jdbc:postgresql://postgres-postgresql:5432/shopsphere

  DB_USERNAME: shopsphere

  DB_PASSWORD: shopsphere123

  JWT_SECRET: OgitEf/qgYdPMj4WhiAdImhyk+Hdjco1h+cEXkM4elE=
