apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: shopsphere
  labels:
    app: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: 047612973664.dkr.ecr.ap-south-1.amazonaws.com/frontend:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 80
